site_name: Zangar
nav:
  - Home: index.md
  - Types: types.md
  - Methods: methods.md
  - Dataclass: dataclass.md
  - Exceptions: exceptions.md
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - macros:
      module_name: docs/macros
