site_name: Zangar
repo_url: https://github.com/Dog-Egg/Zangar
repo_name: Dog-Egg/Zangar
nav:
  - Home: index.md
  - Type Schemas:
      - Primitives: type_schemas/primitives.md
      - Structures: type_schemas/structures.md
      - Dataclasses: type_schemas/dataclasses.md
      - Type Methods: type_schemas/methods.md
  - Messages: messages.md
  - Circular Reference: circular_reference.md
  - Exceptions: exceptions.md
  - Utilities:
      - OpenAPI-Spec Support: openapi.md
theme:
  name: material
  features:
    - navigation.expand
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition

plugins:
  - search
  - macros:
      module_name: docs/macros
