site_name: Zangar
nav:
  - Home: index.md
  - Types: types.md
  - Methods: methods.md
  - Messages: messages.md
  - Dataclass: dataclass.md
  - Circular Reference: circular_reference.md
  - Exceptions: exceptions.md
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition

plugins:
  - macros:
      module_name: docs/macros
